name: SnkCard

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */24 * * *"

jobs:
  snkcard:
    runs-on: ubuntu-latest
    permissions:  # Optional for write permissions
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: snkcard
        uses: Platane/snk@v3
        with:
          github_user_name: techonerd
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Create dist directory if needed
        run: mkdir -p dist

      - name: ensure the generated file exists
        run: |
          ls dist

      - uses: actions/upload-artifact@v3
        with:
          name: github-snake-file
          path: dist/github-snake.svg

      - uses: actions/download-artifact@v3
        with:
          name: github-snake-file
          path: dist/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add generated snake image"
          branch: main
          file_pattern: dist/
